# Generated by Django 5.1.7 on 2025-04-05 15:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrNavypay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('kategori', models.CharField(choices=[('top_up', 'Top Up'), ('pembayaran', 'Pembayaran')], max_length=50, unique=True)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tanggal_transaksi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bill',
            name='status',
        ),
        migrations.RemoveField(
            model_name='billstatus',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='billstatus',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('CF', 'Confirmed'), ('CA', 'Cancelled')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='billstatus',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='BillStatusLog',
            fields=[
                ('last_updated', models.DateTimeField(auto_created=True, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_statuses', to='finance.billstatus')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_id', to='finance.bill')),
            ],
        ),
    ]
