# Generated by Django 5.1.7 on 2025-04-02 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000)),
                ('star_rating', models.DecimalField(decimal_places=0, max_digits=1)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance.bill')),
            ],
        ),
    ]
