# Generated by Django 5.1.7 on 2025-04-05 17:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ocean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatusTransportationService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports_city', to='transportation_service_manager.city')),
                ('ocean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports_ocean', to='transportation_service_manager.ocean')),
            ],
        ),
        migrations.CreateModel(
            name='PortVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('current_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portvisit_current', to='transportation_service_manager.port')),
                ('port_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portvisit_desitnation', to='transportation_service_manager.port')),
            ],
        ),
        migrations.CreateModel(
            name='TransportationService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('port_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportation_service_port_visit', to='transportation_service_manager.portvisit')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportation_service_status', to='transportation_service_manager.statustransportationservice')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('current_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_current_port', to='transportation_service_manager.port')),
            ],
        ),
        migrations.AddField(
            model_name='portvisit',
            name='current_vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portvisit_vehicle', to='transportation_service_manager.vehicle'),
        ),
    ]
