# Generated by Django 5.1.7 on 2025-04-04 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='status',
        ),
        migrations.RemoveField(
            model_name='review',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='bill',
        ),
        migrations.DeleteModel(
            name='BillStatus',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
